name: Android CI

on:
  push:
    branches:
      - '*' # Runs on all branches. Change to your branch name if you want specific branches.
  pull_request:
    branches:
      - '*'

jobs:
  build_android_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 33.0.0

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Android Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk